// Our product database.
const sampleProducts = [
  {
    id: 1,
    name: "Frozen in time",
    author: "Mitchell Zuckoff",
    category: "Adventure",
    description:
      "On November 5, 1942, a US cargo plane slammed into the Greenland Ice Cap. Four days later, the B-17 assigned to the search-and-rescue mission became lost in a blinding storm and also crashed. Miraculously, all nine men on board survived, and the US military launched a daring rescue operation. But after picking up one man, the Grumman Duck amphibious plane flew into a severe storm and vanished.",
    image: "/img/frozen_in_time.jpg",
    pdf: "/pdf/frozen_in_time.pdf",
    popular: true,
    suggested: true,
  },
  {
    id: 2,
    name: "The return of the king",
    author: "J.R.R. Tolkien",
    category: "Adventure",
    description:
      "The Return of the King, the third and final volume in The Lord of the Rings, opens as Gandalf and Pippin ride east to the city of Minas Tirith in Gondor, just after parting with King Théoden and the Riders of Rohan at the end of The Two Towers. In Minas Tirith, Gandalf and Pippin meet Denethor, the city’s Steward, or ruler, who clearly dislikes Gandalf. Pippin offers Denethor his sword in service to Gondor, out of gratitude for the fact that Denethor’s son Boromir gave his life for the hobbits earlier in the quest.",
    image: "/img/return_of_the_king.jpg",
    pdf: "/pdf/return_of_the_king.pdf",
    popular: false,
    suggested: false,
  },
  {
    id: 3,
    name: "The other woman",
    author: "Daniel Silva",
    category: "Adventure",
    description:
      "In an isolated village in the mountains of Andalusia, a mysterious Frenchwoman begins work on a dangerous memoir. It is the story of a man she once loved in the Beirut of old, and a child taken from her in treason’s name. The woman is the keeper of the Kremlin’s most closely guarded secret. Long ago, the KGB inserted a mole into the heart of the West—a mole who stands on the doorstep of ultimate power.",
    image: "/img/the_other_woman.jpg",
    pdf: "/pdf/the_other_woman.pdf",
    popular: false,
    suggested: false,
  },
  {
    id: 4,
    name: "Becoming",
    author: "Michelle Obama",
    category: "Biography",
    description:
      "In her memoir, a work of deep reflection and mesmerizing storytelling, Michelle Obama invites readers into her world, chronicling the experiences that have shaped her - from her childhood on the South Side of Chicago to her years as an executive balancing the demands of motherhood and work, to her time spent at the world's most famous address. With unerring honesty and lively wit, she describes her triumphs and her disappointments, both public and private, telling her full story as she has lived it - in her own words and on her own terms. Warm, wise, and revelatory, Becoming is the deeply personal reckoning of a woman of soul and substance who has steadily defied expectations - and whose story inspires us to do the same.",
    image: "/img/becoming.jpg",
    pdf: "/pdf/becoming.pdf",
    popular: true,
    suggested: false,
  },
  {
    id: 5,
    name: "Elon Musk: Tesla, SpaceX and the Quest for a Fantastic Future",
    author: "Ashlee Vance",
    category: "Biography",
    description:
      "Unique chance to get into the life (and mind) of one of the most interesting guys of the 21st century – Elon Musk. The guy behind PayPal, SpaceX, SolarCity, The Boring Company, and Tesla Motors. How he got started in the business world with companies like PayPal and later SpaceX? What he’s up to now? How does he imagine the future and how dreaming huge (not only big) can make you a modern superstar?",
    image: "/img/elon_musk.jpg",
    pdf: "/pdf/elon_musk.pdf",
    popular: true,
    suggested: false,
  },
  {
    id: 6,
    name: "The World as I see it",
    author: "Albert Einstein",
    category: "Biography",
    description:
      "Einstein has expressed his personal views about the purpose and ideals of life, democracy and dictatorship, war and peace, mystery and religion. Einstein says that our stay in this world is very short. The life is not purposeless. We live for the sake of fellow beings because our happiness depends on the smiles and welfare of others. He thinks that his fellowman work very hard in order to make his life comfortable, so he must repay in the same measure.",
    image: "/img/einstein.jpg",
    pdf: "/pdf/einstein.pdf",
    popular: false,
    suggested: false,
  },
  {
    id: 7,
    name: "The Cabin of the End of the World",
    author: "Paul Tremblay",
    category: "Horror",
    description:
      "The Cabin at the End of the World plays out at a break-neck pace, with its events taking place over the course of one frightening day. We’re introduced to a seven-year-old girl named Wen, adopted from China by a gay couple (Daddy Eric and Daddy Andrew). Wen is an inquisitive kid who takes the family’s vacation to off-the-grid New Hampshire seriously, studying grasshoppers and having fun being away from school. While she’s out collecting bugs, she’s approached by a large man named Leonard, who tells her that he wants to be her friend, and that he and his friends need to have a chat with the family. She flees to the house, and her parents try unsuccessfully to keep the four people — Leonard, Redmond, Sabrina, and Adriane — out.",
    image: "/img/cabin_paul.jpg",
    pdf: "/pdf/cabin_paul.pdf",
    popular: true,
    suggested: false,
  },
  {
    id: 8,
    name: "Intercepts",
    author: "T.J. Payne",
    category: "Horror",
    description:
      "Joe's teenage daughter is suddenly experiencing terrifying hallucinations. She sees a woman in a hospital gown in her bedroom, screaming and clawing the skin from her own face. Either Joe’s daughter is having a mental breakdown… or her mind has been intercepted by the patients at the secret facility where Joe works.",
    image: "/img/intercepts.png",
    pdf: "/pdf/intercepts.pdf",
    popular: false,
    suggested: false,
  },
  {
    id: 9,
    name: "Outliers",
    author: "Malcolm Gladwell",
    category: "Leadership",
    description:
      "Malcolm Gladwell’s Outliers examines the nature of success using various success stories as case studies. Gladwell begins by exploring what we tend to think about particularly successful people: famous athletes, multi-millionaires, Nobel Prize winners, or titans of business, for example. He notes that we tend to believe in the predominance of “individual merit.” We believe people are unusually successful because they are unusually gifted. They possess innate talent, drive, and determination, and they are rewarded with great success.",
    image: "/img/outliers.png",
    pdf: "/pdf/outliers.pdf",
    popular: false,
    suggested: false,
  },
  {
    id: 10,
    name: "How successful people think",
    author: "John C. Maxwell",
    category: "Leadership",
    description:
      "This book starts out with the statement, “The person who knows how will always have a job, but the person who knows why will always be his boss.” If you can change the way you think, you can change your life. Good thinkers rarely find themselves being victimized by the world’s dictators and connivers…they know what they think and are confident.",
    image: "/img/john_maxwell.jpg",
    pdf: "/pdf/john_maxwell.pdf",
    popular: false,
    suggested: true,
  },
  {
    id: 11,
    name: "The monk who sold his Ferrari",
    author: "Robin S. Sharma",
    category: "Leadership",
    description:
      "In this eagerly awaited sequel to the phenomenal national bestseller The Monk Who Sold His Ferrari, leadership guru and renowned professional speaker Robin S. Sharma shares a remarkable step-by-step system that will transform the way you lead your team and renew trust, commitment and hope within your organization. With masterful insight and brilliant simplicity, Sharma has distilled timeless wisdom for visionary leadership into a series of immensely practical lessons that leaders, managers and entrepreneurs can immediately apply to boost morale, liberate loyalty and send productivity soaring in these topsy-turvy times.",
    image: "/img/ferrari.jpg",
    pdf: "/pdf/ferrari.pdf",
    popular: true,
    suggested: true,
  },
  {
    id: 12,
    name: "The business of 21st century",
    author: "Robert T. Kiyosaki",
    category: "Leadership",
    description:
      "The book harps on the belief that each person should be responsible for his own finances. He should not depend on what is happening to the economy, because wealth-building has nothing to do with it. He should be the master of his money instead of being a slave to it. Through his meticulous research work, the author lays down the steps to take in order to achieve financial stability and amass genuine wealth. The book also discusses an easy and effective business model which is compatible for those who are courageous enough to go into business. ",
    image: "/img/21st_century.jpg",
    pdf: "/pdf/21st_century.pdf",
    popular: false,
    suggested: false,
  },
  {
    id: 13,
    name: "Beyond positive thinking",
    author: "Dr. Robert Anthony",
    category: "Motivational",
    description:
      "This book is a step-by-step process for “right thinking” rather than “positive thinking.” It doesn’t pull any punches regarding why you do the things you do that sabotage your goals. And it specifically tells you what to do about them, so you can achieve your dreams.",
    image: "/img/robert_anthony.jpg",
    pdf: "/pdf/robert_anthony.pdf",
    popular: false,
    suggested: true,
  },
  {
    id: 14,
    name: "The power of positive thinking",
    author: "Norman Vincent Peale",
    category: "Motivational",
    description:
      "In The Power of Positive Thinking, Norman Vincent Peale says there is no problem or obstacle you can’t overcome with faith, positive thinking, and prayer. The book outlines the practical techniques of applied Christianity to help you take control of the events in your life rather than be directed by them. As a result of these methods, you can enjoy better relationships, a greater sense of well-being, robust health and energy, and a stronger sense of purpose in the world.",
    image: "/img/positive_thinking.jpg",
    pdf: "/pdf/positive_thinking.pdf",
    popular: false,
    suggested: false,
  },
  {
    id: 15,
    name: "No excuses! The power of self-discipline",
    author: "Brian Tracy",
    category: "Motivational",
    description:
      "In this ambitious work, Brian Tracy presents a formula for overcoming life’s major challenges. It boils down to applying self-discipline to achieve overall success and happiness. Tracy’s topics range from acting with integrity to making sales to strengthening your marriage. With such a broad span, his advice is necessarily general and elementary. However, if you avoid looking for specific solutions, and focus on the overall theme of the book, you will find it quite helpful. Tracy espouses that you need to accept responsibility for your own contentment and career. ",
    image: "/img/no_excuses.jpg",
    pdf: "/pdf/no_excuses.pdf",
    popular: true,
    suggested: true,
  },
  {
    id: 16,
    name: "Switch - How to change things when change is hard",
    author: "Chip & Dan Heath",
    category: "Motivational",
    description:
      "Switch is about how you can lead and encourage changes of human behavior, both in yourself and in your organization, by focusing on the three forces that influence it: the rider, the elephant and the path.",
    image: "/img/switch.jpg",
    pdf: "/pdf/switch.pdf",
    popular: true,
    suggested: true,
  },
  {
    id: 17,
    name: "The fifth mountain",
    author: "Paulo Coehlo",
    category: "Motivational",
    description:
      "The Fifth Mountain is a work of historical fiction by Brazilian novelist and lyricist Paulo Coelho. A fictionalized version of the biblical story of the Prophet Elijah, it relates his struggle to spread the word of God in Israel after he experiences a series of powerful visions. At first, Elijah is afraid to follow his vocation as a prophet, having been taught by his parents to prioritize the secular world and his career over God. Coelho connects this story from the 900’s B.C. to modern themes, including political refugeeism, existential anxiety, alienation, and crisis of faith.",
    image: "/img/fifth_mountain.jpg",
    pdf: "/pdf/fifth_mountain.pdf",
    popular: false,
    suggested: false,
  },
  {
    id: 18,
    name: "Eat that frog!",
    author: "Brian Tracy",
    category: "Personal development",
    description:
      "There's an old saying: if you eat a live frog first thing each morning, you'll have the satisfaction of knowing that it's probably the worst thing you'll do all day. Using eat that frog as a metaphor for tackling the most challenging task of your day, the one you are most likely to procrastinate on, but also the one that might have the greatest positive impact on your life, Eat That Frog! shows you how to zero in on these critical tasks and organize your day. You'll not only get more done faster, but get the right things done.",
    image: "/img/eat_that_frog.jpg",
    pdf: "/pdf/eat_that_frog.pdf",
    popular: true,
    suggested: true,
  },
  {
    id: 19,
    name: "The art of saying no",
    author: "Damon Zahariades",
    category: "Personal development",
    description:
      "Stop Being A People Pleaser! Learn How To Set Boundaries And Say NO - Without Feeling Guilty! Are you fed up with people taking advantage of you? Are you tired of coworkers, friends, and family members demanding your time and expecting you to give it to them?If so, THE ART OF SAYING NO is for you.Imagine being able to turn down requests and decline invitations with confidence and poise . Imagine saying no to people asking you for favors, and inspiring their respect in the process ",
    image: "/img/art_of_saying_no.jpg",
    pdf: "/pdf/art_of_saying_no.pdf",
    popular: true,
    suggested: true,
  },
  {
    id: 20,
    name: "Women who think too much",
    author: "Dr. Susan Nolen-Hoeksema",
    category: "Personal development",
    description:
      "In Women Who Think Too Much, Nolen-Hoeksema shows us what causes so many women to be overthinkers and provides concrete strategies that can be used to escape these negative thoughts, move to higher ground, and live more productively. Women Who Think Too Much will change lives, and is destined to become a self-help classic",
    image: "/img/women.jpg",
    pdf: "/pdf/women.pdf",
    popular: false,
    suggested: false,
  },
];

// List of item categories.
const categories = [
  { name: "All categories" },
  { name: "Adventure" },
  { name: "Biography" },
  { name: "Horror" },
  { name: "Leadership" },
  { name: "Motivational" },
  { name: "Personal development" },
];

export { sampleProducts, categories };
